# Build image using Buildah action
name: Build Image
inputs:
  image-name:
    required: true
  alias-tags:
    required: true
  labels:
    required: true
outputs:
  image:
    value: ${{ steps.build_image.outputs.image }}
  tags:
    value: ${{ steps.build_image.outputs.tags }}
runs:
  using: "composite"
  steps:
    - name: Copy Files
      id: copy_files
      shell: bash
      run: |
        cp -r wmbazzite/* ./
    - id: build_image
      shell: bash
      run: |
        sudo buildah build \
          --build-arg IMAGE_NAME=${{ env.IMAGE_NAME }} \
          --build-arg IMAGE_VENDOR=${{ github.repository_owner }} \
          --build-arg BASE_IMAGE_NAME=Bazzite \
          --build-arg BASE_IMAGE_FLAVOR=DX \
          --build-arg FEDORA_MAJOR_VERSION=${{ env.FEDORA_VERSION }} \
          --build-arg FEDORA_VERSION=${{ env.FEDORA_VERSION }} \
          --build-arg IMAGE_BRANCH=${{ github.ref_name }} \
          --build-arg SHA_HEAD_SHORT=${{ env.SHA_HEAD_SHORT }} \
          --build-arg VERSION_TAG=${{ env.DEFAULT_TAG }} \
          --build-arg VERSION_PRETTY="${{ env.DEFAULT_TAG }}" \
          --tag ${{ env.IMAGE_NAME }} .
