# Build image using Buildah action
name: Build Image
id: build_image
uses: redhat-actions/buildah-build@v2
working-directory: ./wmbazzite
with:
  containerfiles: |
    ./Containerfile
  # Postfix image name with -custom to make it a little more descriptive
  # Syntax: https://docs.github.com/en/actions/learn-github-actions/expressions#format
  image: ${{ env.MY_IMAGE_NAME }}
  tags: |
    ${{ steps.generate-tags.outputs.alias_tags }}
  labels: ${{ steps.meta.outputs.labels }}
  oci: false
