# Build image using Buildah action
name: Build Image
inputs:
  image-name:
    required: true
  alias-tags:
    required: true
  labels:
    required: true
outputs:
  image:
    value: ${{ steps.build_image.outputs.image }}
  tags:
    value: ${{ steps.build_image.outputs.tags }}
runs:
  using: "composite"
  steps:
    - id: copy_files
      run: |
        cp * ..
    - id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: |
          ./Containerfile
        # Postfix image name with -custom to make it a little more descriptive
        # Syntax: https://docs.github.com/en/actions/learn-github-actions/expressions#format
        image: ${{ inputs.image-name }}
        tags: |
          ${{ inputs.alias-tags }}
        labels: ${{ inputs.labels }}
        oci: false
