FROM quay.io/fedora/fedora:latest

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="An image intended to be used as a base for linux development"

COPY ./fedora-dev/build.sh /tmp/build.sh

RUN /tmp/build.sh

RUN rm -rf /tmp/*
